import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import ThemeLayout from "@/components/ThemeLayout";
import "./globals.css";

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${roboto.className} light`}>
        <ThemeLayout>{children}</ThemeLayout>
      </body>
    </html>
  );
}
